package com.example.hegemony.domain.model;

public enum ActionType {
    ADVANCE_TO_VOTING,
    ADVANCE_TO_PRODUCTION,
    RESOLVE_PRODUCTION_PHASE,
    ADVANCE_TO_SCORING,
    RESOLVE_SCORING_PHASE,
    ADVANCE_TO_NEXT_ROUND,
    RESOLVE_PREPARATION_PHASE,
    ADVANCE_GAME_FLOW,
    ADVANCE_ROUND,
    DECLARE_VOTE_STANCE,
    COMMIT_VOTE_INFLUENCE,

    PROPOSE_BILL,
    ADD_VOTING_CUBES,
    CALL_EXTRAORDINARY_VOTE,
    ASSIGN_WORKERS,
    PLACE_STRIKES,
    PLACE_DEMONSTRATION,
    BUY_GOODS_AND_SERVICES,
    CONSUME_HEALTHCARE,
    CONSUME_EDUCATION,
    CONSUME_LUXURY,
    REFRESH_BUSINESS_DEALS,

    // Legacy demo actions kept for explicit non-core mode/backward compatibility.
    START_TURN,
    HIRE_WORKER,
    PRODUCE_GOODS,
    SELL_GOODS,
    ADJUST_POLICY,
    PLAY_CARD,
    END_TURN
}
